---
import_mode: Batch - Directory Only
base_directory: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN
file_configs:
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/barrels_custom_shape.inp
  network_name: InfoWorks - OWA_EXTRAN_barrels_custom_shape
  file_basename: barrels_custom_shape.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/bug_item11_swmm5.1.014_more_links_than_nodes
    (1).inp
  network_name: InfoWorks - OWA_EXTRAN_bug_item11_swmm5.1.014_more_links_than_nodes
    (1)
  file_basename: bug_item11_swmm5.1.014_more_links_than_nodes (1).inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/bug_item11_swmm5.1.014_more_links_than_nodes
    (2).inp
  network_name: InfoWorks - OWA_EXTRAN_bug_item11_swmm5.1.014_more_links_than_nodes
    (2)
  file_basename: bug_item11_swmm5.1.014_more_links_than_nodes (2).inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/bug_item11_swmm5.1.014_more_links_than_nodes(1).inp
  network_name: InfoWorks - OWA_EXTRAN_bug_item11_swmm5.1.014_more_links_than_nodes(1)
  file_basename: bug_item11_swmm5.1.014_more_links_than_nodes(1).inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/bug_item11_swmm5.1.014_more_links_than_nodes.inp
  network_name: InfoWorks - OWA_EXTRAN_bug_item11_swmm5.1.014_more_links_than_nodes
  file_basename: bug_item11_swmm5.1.014_more_links_than_nodes.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/bug_item8_link_seepage.inp
  network_name: InfoWorks - OWA_EXTRAN_bug_item8_link_seepage
  file_basename: bug_item8_link_seepage.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EDSYPHON.inp
  network_name: InfoWorks - OWA_EXTRAN_EDSYPHON
  file_basename: EDSYPHON.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/emc_exam1.inp
  network_name: InfoWorks - OWA_EXTRAN_emc_exam1
  file_basename: emc_exam1.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EPANET_SWMMHazenWilliamscomparison.inp
  network_name: InfoWorks - OWA_EXTRAN_EPANET_SWMMHazenWilliamscomparison
  file_basename: EPANET_SWMMHazenWilliamscomparison.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/exam1.inp
  network_name: InfoWorks - OWA_EXTRAN_exam1
  file_basename: exam1.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM12_SW5.INP
  network_name: InfoWorks - OWA_EXTRAN_EXAM12_SW5
  file_basename: EXAM12_SW5.INP
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM1_45_days_SW5.INP
  network_name: InfoWorks - OWA_EXTRAN_EXAM1_45_days_SW5
  file_basename: EXAM1_45_days_SW5.INP
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM1_ICM.inp
  network_name: InfoWorks - OWA_EXTRAN_EXAM1_ICM
  file_basename: EXAM1_ICM.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/exam1_negative_flow_examples.inp
  network_name: InfoWorks - OWA_EXTRAN_exam1_negative_flow_examples
  file_basename: exam1_negative_flow_examples.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM1_no_adverse_slopes_SW5.INP
  network_name: InfoWorks - OWA_EXTRAN_EXAM1_no_adverse_slopes_SW5
  file_basename: EXAM1_no_adverse_slopes_SW5.INP
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM1_OUTLET_Curve_SI.inp
  network_name: InfoWorks - OWA_EXTRAN_EXAM1_OUTLET_Curve_SI
  file_basename: EXAM1_OUTLET_Curve_SI.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/exam1_PID_Freeboard.inp
  network_name: InfoWorks - OWA_EXTRAN_exam1_PID_Freeboard
  file_basename: exam1_PID_Freeboard.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM1_SW5.inp
  network_name: InfoWorks - OWA_EXTRAN_EXAM1_SW5
  file_basename: EXAM1_SW5.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM1_SW5_external_load_of_tss.inp
  network_name: InfoWorks - OWA_EXTRAN_EXAM1_SW5_external_load_of_tss
  file_basename: EXAM1_SW5_external_load_of_tss.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM21_SW5.inp
  network_name: InfoWorks - OWA_EXTRAN_EXAM21_SW5
  file_basename: EXAM21_SW5.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM25_SW5.INP
  network_name: InfoWorks - OWA_EXTRAN_EXAM25_SW5
  file_basename: EXAM25_SW5.INP
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM2_long_step_SW5.inp
  network_name: InfoWorks - OWA_EXTRAN_EXAM2_long_step_SW5
  file_basename: EXAM2_long_step_SW5.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM2_WITH_Fixed_Stage.inp
  network_name: InfoWorks - OWA_EXTRAN_EXAM2_WITH_Fixed_Stage
  file_basename: EXAM2_WITH_Fixed_Stage.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM2_with_numerical_problem_SW5.inp
  network_name: InfoWorks - OWA_EXTRAN_EXAM2_with_numerical_problem_SW5
  file_basename: EXAM2_with_numerical_problem_SW5.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM2_WITH_TIDE_SW5.inp
  network_name: InfoWorks - OWA_EXTRAN_EXAM2_WITH_TIDE_SW5
  file_basename: EXAM2_WITH_TIDE_SW5.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM30_SW5.inp
  network_name: InfoWorks - OWA_EXTRAN_EXAM30_SW5
  file_basename: EXAM30_SW5.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM32_SW5.inp
  network_name: InfoWorks - OWA_EXTRAN_EXAM32_SW5
  file_basename: EXAM32_SW5.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM60_SW5.INP
  network_name: InfoWorks - OWA_EXTRAN_EXAM60_SW5
  file_basename: EXAM60_SW5.INP
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM70_SW5.INP
  network_name: InfoWorks - OWA_EXTRAN_EXAM70_SW5
  file_basename: EXAM70_SW5.INP
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM7_with_pump3_SW5.INP
  network_name: InfoWorks - OWA_EXTRAN_EXAM7_with_pump3_SW5
  file_basename: EXAM7_with_pump3_SW5.INP
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM7_with_pump3_TS_Rule.inp
  network_name: InfoWorks - OWA_EXTRAN_EXAM7_with_pump3_TS_Rule
  file_basename: EXAM7_with_pump3_TS_Rule.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM80a.INP
  network_name: InfoWorks - OWA_EXTRAN_EXAM80a
  file_basename: EXAM80a.INP
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/EXAM80_Storage.inp
  network_name: InfoWorks - OWA_EXTRAN_EXAM80_Storage
  file_basename: EXAM80_Storage.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran1.inp
  network_name: InfoWorks - OWA_EXTRAN_extran1
  file_basename: extran1.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran10.inp
  network_name: InfoWorks - OWA_EXTRAN_extran10
  file_basename: extran10.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran10_slot.inp
  network_name: InfoWorks - OWA_EXTRAN_extran10_slot
  file_basename: extran10_slot.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran1_circular.inp
  network_name: InfoWorks - OWA_EXTRAN_extran1_circular
  file_basename: extran1_circular.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran1_circular_100_feet_long.inp
  network_name: InfoWorks - OWA_EXTRAN_extran1_circular_100_feet_long
  file_basename: extran1_circular_100_feet_long.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran1_control_rules.inp
  network_name: InfoWorks - OWA_EXTRAN_extran1_control_rules
  file_basename: extran1_control_rules.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran1_control_rules_wq.inp
  network_name: InfoWorks - OWA_EXTRAN_extran1_control_rules_wq
  file_basename: extran1_control_rules_wq.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran1_negative_depth.inp
  network_name: InfoWorks - OWA_EXTRAN_extran1_negative_depth
  file_basename: extran1_negative_depth.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran1_rectangular.inp
  network_name: InfoWorks - OWA_EXTRAN_extran1_rectangular
  file_basename: extran1_rectangular.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran1_slot.inp
  network_name: InfoWorks - OWA_EXTRAN_extran1_slot
  file_basename: extran1_slot.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran2.inp
  network_name: InfoWorks - OWA_EXTRAN_extran2
  file_basename: extran2.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran2_slot.inp
  network_name: InfoWorks - OWA_EXTRAN_extran2_slot
  file_basename: extran2_slot.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran3.inp
  network_name: InfoWorks - OWA_EXTRAN_extran3
  file_basename: extran3.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran3_dummy_link.inp
  network_name: InfoWorks - OWA_EXTRAN_extran3_dummy_link
  file_basename: extran3_dummy_link.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran3_dummy_links.inp
  network_name: InfoWorks - OWA_EXTRAN_extran3_dummy_links
  file_basename: extran3_dummy_links.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran3_noInflow.inp
  network_name: InfoWorks - OWA_EXTRAN_extran3_noInflow
  file_basename: extran3_noInflow.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran3_noInflow_circular_outfall.inp
  network_name: InfoWorks - OWA_EXTRAN_extran3_noInflow_circular_outfall
  file_basename: extran3_noInflow_circular_outfall.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran3_RC.inp
  network_name: InfoWorks - OWA_EXTRAN_extran3_RC
  file_basename: extran3_RC.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran3_RTC.inp
  network_name: InfoWorks - OWA_EXTRAN_extran3_RTC
  file_basename: extran3_RTC.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran3_RTC_Rule.inp
  network_name: InfoWorks - OWA_EXTRAN_extran3_RTC_Rule
  file_basename: extran3_RTC_Rule.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran3_slot.inp
  network_name: InfoWorks - OWA_EXTRAN_extran3_slot
  file_basename: extran3_slot.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran4.inp
  network_name: InfoWorks - OWA_EXTRAN_extran4
  file_basename: extran4.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran4_roadway.inp
  network_name: InfoWorks - OWA_EXTRAN_extran4_roadway
  file_basename: extran4_roadway.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran4_slot.inp
  network_name: InfoWorks - OWA_EXTRAN_extran4_slot
  file_basename: extran4_slot.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran4_slot_outlet_bc.inp
  network_name: InfoWorks - OWA_EXTRAN_extran4_slot_outlet_bc
  file_basename: extran4_slot_outlet_bc.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran4_slot_outlet_link.inp
  network_name: InfoWorks - OWA_EXTRAN_extran4_slot_outlet_link
  file_basename: extran4_slot_outlet_link.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran4_slot_zero_width.inp
  network_name: InfoWorks - OWA_EXTRAN_extran4_slot_zero_width
  file_basename: extran4_slot_zero_width.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran5.inp
  network_name: InfoWorks - OWA_EXTRAN_extran5
  file_basename: extran5.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran5_slot.inp
  network_name: InfoWorks - OWA_EXTRAN_extran5_slot
  file_basename: extran5_slot.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran6.inp
  network_name: InfoWorks - OWA_EXTRAN_extran6
  file_basename: extran6.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran6_slot.inp
  network_name: InfoWorks - OWA_EXTRAN_extran6_slot
  file_basename: extran6_slot.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran6_type1.inp
  network_name: InfoWorks - OWA_EXTRAN_extran6_type1
  file_basename: extran6_type1.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran7.inp
  network_name: InfoWorks - OWA_EXTRAN_extran7
  file_basename: extran7.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran7_high_pump_rate.inp
  network_name: InfoWorks - OWA_EXTRAN_extran7_high_pump_rate
  file_basename: extran7_high_pump_rate.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran7_rules.inp
  network_name: InfoWorks - OWA_EXTRAN_extran7_rules
  file_basename: extran7_rules.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran7_slot.inp
  network_name: InfoWorks - OWA_EXTRAN_extran7_slot
  file_basename: extran7_slot.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran7_type3_high_pump_rate.inp
  network_name: InfoWorks - OWA_EXTRAN_extran7_type3_high_pump_rate
  file_basename: extran7_type3_high_pump_rate.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran8a.inp
  network_name: InfoWorks - OWA_EXTRAN_extran8a
  file_basename: extran8a.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran8a_slot.inp
  network_name: InfoWorks - OWA_EXTRAN_extran8a_slot
  file_basename: extran8a_slot.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran8b.inp
  network_name: InfoWorks - OWA_EXTRAN_extran8b
  file_basename: extran8b.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran8b_slot.inp
  network_name: InfoWorks - OWA_EXTRAN_extran8b_slot
  file_basename: extran8b_slot.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran9.inp
  network_name: InfoWorks - OWA_EXTRAN_extran9
  file_basename: extran9.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran9_slot.inp
  network_name: InfoWorks - OWA_EXTRAN_extran9_slot
  file_basename: extran9_slot.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/extran9_with_slash.inp
  network_name: InfoWorks - OWA_EXTRAN_extran9_with_slash
  file_basename: extran9_with_slash.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/longTS_extran1.inp
  network_name: InfoWorks - OWA_EXTRAN_longTS_extran1
  file_basename: longTS_extran1.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/mod_extran1.inp
  network_name: InfoWorks - OWA_EXTRAN_mod_extran1
  file_basename: mod_extran1.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/PumpRTC_exam1.inp
  network_name: InfoWorks - OWA_EXTRAN_PumpRTC_exam1
  file_basename: PumpRTC_exam1.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/SI_very_simple_cfs_flow_import_ICM_SWMM.inp
  network_name: InfoWorks - OWA_EXTRAN_SI_very_simple_cfs_flow_import_ICM_SWMM
  file_basename: SI_very_simple_cfs_flow_import_ICM_SWMM.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\OWA_EXTRAN/very_simple_cfs_flow_import_ICM_SWMM.inp
  network_name: InfoWorks - OWA_EXTRAN_very_simple_cfs_flow_import_ICM_SWMM
  file_basename: very_simple_cfs_flow_import_ICM_SWMM.inp
database_guid: CF4976F1-E477-4199-9E21-3F2A6A383318
timestamp: '2025-10-29 19:32:36 -0400'
file_type: SWMM5
cleanup_empty_label_lists: true
validate_after_import: true
