---
import_mode: Batch - Include Subdirectories
base_directory: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\Greenville
file_configs:
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\Greenville/Greenville_all_SWMM5_Features.inp
  model_group_name: SWMM5 - Greenville_all_SWMM5_Features
  file_basename: Greenville_all_SWMM5_Features.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\Greenville/Greenville_all_SWMM5_Features_SI_Units.inp
  model_group_name: SWMM5 - Greenville_all_SWMM5_Features_SI_Units
  file_basename: Greenville_all_SWMM5_Features_SI_Units.inp
- file_path: C:\Users\dickinro\OneDrive - Autodesk\Documents\GitHub\1729-SWMM5-Models\Greenville/Greenville_small_snowmelt_model.inp
  model_group_name: SWMM5 - Greenville_small_snowmelt_model
  file_basename: Greenville_small_snowmelt_model.inp
database_guid: 4647B962-BDBB-4EC7-884E-C52C6604A458
timestamp: '2025-11-21 10:28:02 -0500'
file_type: SWMM5
cleanup_empty_label_lists: true
validate_after_import: true
